---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.9
    - tip
  install:
    - go get github.com/golang/lint/golint
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"